# Generated by Django 4.2.20 on 2025-04-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='otp_code',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=254),
        ),
    ]
